"""empty message

Revision ID: 85316732cd82
Revises: adf65fe3bbd2
Create Date: 2025-02-27 21:44:00.577357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85316732cd82'
down_revision = 'adf65fe3bbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('img_profile', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img_profile')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
